### ISSUE TITLE
build arm image

### ISSUE THREAD

**Issue by januschung** [januschung/job-winner-ui#129]
so that I can use it on OCI vm

```
- name: Build and push
  uses: docker/build-push-action@v6
  with:
    context: .
    push: true
    platforms: linux/amd64,linux/arm64
    tags: |
      ghcr.io/januschung/job-winner-ui:${{ env.COMMIT_SHA }}
      ghcr.io/januschung/job-winner-ui:latest
```
